version: '3'

networks:
  tutorial:
    name: tutorial # The docker network to connect the different containers

services:
  mongodb:
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - "27017:27017" # The port to access MongoDB

  mongo_express:
    image: mongo-express
    networks:
      - tutorial
    ports:
      - target: 8081
        published: 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb # The address of the mongodb server. Docker enginer will resolve the name to the IP address.
    command: /bin/bash -c "sleep 60 && /docker-entrypoint.sh mongo-express" # We wait 60 seconds to start as the MongoDB needs time to start
    depends_on:
      - mongodb
