version: '3'

networks:
  tutorial:
    name: tutorial

services:
  mongodb1: # mongoDB data store 1. The data is stored in MongoDB1 and MongoDB1
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27017
    command: mongod --shardsvr --replSet clustershard --port 27017

  mongodb2: # mongoDB data store 2
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27018
    command: mongod --shardsvr --replSet clustershard --port 27017
    depends_on:
      - mongodb1

  mongocf: # Mongo config. It manages the configuration and metadata of the sharding. It can be also set up as a cluster.
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27019
    command: mongod --configsvr --replSet clustercf --port 27017
    depends_on:
      - mongodb1
      - mongodb2

  mongos: # Mongos acts as a router and also manages the sharding
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - target: 27017
        published: 27021
    command: mongos --configdb clustercf/mongocf:27017 --port 27017 --bind_ip_all
    depends_on:
      - mongocf
