version: '3'

networks:
  tutorial:
    name: tutorial

services:
  mongodb:
    image: mongo:4.2.24-bionic
    networks:
      - tutorial
    ports:
      - "27017:27017"
    volumes:
      - .:/tutorial # This will give access the docker container to the current directory in order to access the restaurants.json file

  mongo_express:
    image: mongo-express
    networks:
      - tutorial
    ports:
      - target: 8081
        published: 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    command: /bin/bash -c "sleep 60 && /docker-entrypoint.sh mongo-express"
    depends_on:
      - mongodb