version: '3'

networks:
  tutorial:
    name: tutorial # The docker network to connect containers together

services:
  cassandra:
    image: cassandra:latest
    networks:
      - tutorial
    ports:
      - "9042:9042" # The port for client connections